import Foundation
import Testing

@Test func buildAppScriptUsesFinderCompatibleIconMetadata() throws {
    let packageRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
    let scriptURL = packageRoot.appendingPathComponent("scripts/build-app.sh")
    let script = try String(contentsOf: scriptURL, encoding: .utf8)
    let appSourceURL = packageRoot.appendingPathComponent("Sources/WonderShowApp/WonderShowApplication.swift")
    let appSource = try String(contentsOf: appSourceURL, encoding: .utf8)
    let communityPackageScriptURL = packageRoot.appendingPathComponent("scripts/package-community-app.sh")
    let communityPackageScript = try String(contentsOf: communityPackageScriptURL, encoding: .utf8)
    let openSourcePackageScriptURL = packageRoot.appendingPathComponent("scripts/package-open-source-kit.sh")
    let openSourcePackageScript = try String(contentsOf: openSourcePackageScriptURL, encoding: .utf8)
    let entitlementsURL = packageRoot.appendingPathComponent("packaging/WonderShow.entitlements")
    let entitlements = try String(contentsOf: entitlementsURL, encoding: .utf8)

    #expect(script.contains("AppIcon.icns"))
    #expect(script.contains("APP_NAME=\"${APP_NAME:-灵演}\""))
    #expect(script.contains("APP_NAME=\"${APP_NAME:-灵演社区版}\""))
    #expect(script.contains("BUNDLE_IDENTIFIER=\"${BUNDLE_IDENTIFIER:-com.wondershow.studio}\""))
    #expect(script.contains("BUNDLE_IDENTIFIER=\"${BUNDLE_IDENTIFIER:-com.wondershow.community}\""))
    #expect(script.contains("EXECUTABLE=\"${EXECUTABLE:-WonderShowStudio}\""))
    #expect(script.contains("EXECUTABLE=\"${EXECUTABLE:-WonderShowCommunity}\""))
    #expect(script.contains("CAMERA_USAGE_DESCRIPTION=\"灵演社区版需要访问摄像头，用于录制讲者画面。\""))
    #expect(script.contains("MICROPHONE_USAGE_DESCRIPTION=\"灵演社区版需要访问麦克风，用于录制讲者声音并合成视频。\""))
    #expect(script.contains("APPLE_EVENTS_USAGE_DESCRIPTION=\"灵演社区版需要控制 Keynote、PowerPoint 或浏览器，用于演示播放和录制辅助操作。\""))
    #expect(script.contains("BUILD_EXECUTABLE=\"$ROOT_DIR/.build/arm64-apple-macosx/$BUILD_CONFIGURATION/WonderShowApp\""))
    #expect(script.contains("WonderShow_WonderShowApp.bundle"))
    #expect(script.contains("CFBundleIdentifier -string \"$BUNDLE_IDENTIFIER\""))
    #expect(script.contains("cp -R \"$RESOURCE_BUNDLE\" \"$BUNDLE_DIR/Contents/Resources/\""))
    #expect(script.contains("find \"$BUNDLE_DIR/Contents/Resources\" -name \"WonderShow.entitlements\" -type f -delete"))
    #expect(script.contains("WonderShowEdition"))
    #expect(appSource.contains("Window(WonderShowDistribution.windowTitle"))
    #expect(communityPackageScript.contains("COMMUNITY_EDITION"))
    #expect(communityPackageScript.contains("shasum -a 256 \"$(basename \"$OUTPUT_ZIP\")\""))
    #expect(openSourcePackageScript.contains("shasum -a 256 \"$(basename \"$OUTPUT_ZIP\")\""))
    #expect(script.contains("swift_build_args=(-c \"$BUILD_CONFIGURATION\" --disable-sandbox)"))
    #expect(script.contains("swift build \"${swift_build_args[@]}\""))
    #expect(!script.contains("swift build -c \"$BUILD_CONFIGURATION\" --disable-sandbox \"${SWIFT_FLAGS[@]}\""))
    #expect(script.contains("ENTITLEMENTS_FILE="))
    #expect(script.contains("--entitlements \"$ENTITLEMENTS_FILE\""))
    #expect(script.contains("--options runtime"))
    #expect(script.contains("strip -S -x"))
    #expect(script.contains("CFBundleIconFile -string \"AppIcon\""))
    #expect(script.contains("PkgInfo"))
    #expect(!script.contains("CFBundleIconName"))
    #expect(!script.contains("com.local.LingYan"))
    #expect(entitlements.contains("com.apple.security.device.camera"))
    #expect(entitlements.contains("com.apple.security.device.audio-input"))
    #expect(entitlements.contains("com.apple.security.automation.apple-events"))
}
